### ISSUE TITLE
[Feature Request] Sid

### ISSUE THREAD

**Issue by ssj71** [pgiblock/lmms-lv2#1]
Hi Pgib,
   I was talking to someone on IRC who wants a SID6586 LV2 plugin. I was already aware of your porting project here, but in the readme you mention the SID plugin isn't not much of a priority. I would also like to see this done and was looking at the lmms and your source here. I could maybe contribute the port, but I'm having a little difficulty telling how exactly you are using the lmms plugins source (I only looked for about 10 minutes though). What functions do I need to wrap and how? It just seems that your code is changed quite a bit from the original source so for me to do the same and keep the code consistent will need some guidance.

   I'm also curious why you chose C. Even though i prefer C, I would think C++ would allow better code reuse between lmms and the lv2 plugins. I was thinking of just editing the instrument_track object from lmms to be an lv2 plugin and hopefully not change any of the plugins' code at all. I imagine this will result in a very large plugin, but it would be able to use the artwork and everything straight from lmms with minimal changes. I'm just starting to research this so I don't know if it will even work, or if the GUI is too tightly integrated or something else entirely. I figured you have a much better idea since you've worked on lmms and you chose to go the route you did. Thanks in advance.

Also, sorry this isn't really a good feature request/issue, but it was the only way I could send some sort of message to you.

**Comment by pgiblock** [comment]
Hello,

This is a good question, at least: "Why is the code for LMMS-LV2 so 
diverged from the original LMMS" code.  I can answer that.  Now, it is 
true that we could emulate a number of LMMS's interfaces to aide in 
porting of the plugins, but we can't do that everywhere.  I took this 
sort of "adopt code in chunks so plugins don't need to change to much" 
approach in the start, but found that it was very difficult to determine 
which code is important, and what some code even did.  Because of this, 
I used the LMMS code as more of a pseudo-code.  You'll find I also have 
some different goals, by design:

LMMS uses a system where MIDI note information is allocated, queued, and 
deleted for each note. This involves unsafe and expensive malloc and 
locking functions.  LMMS-LV2 uses a simple event-loop with a number of 
preallocated "voices".  Perhaps the LMMS interface could be emulated to 
a degree, but this seems like a backwards way to approach the problem. 
LMMS only supports control changes on processing buffer size boundaries 
(say 256 samples or so), the approach used by LMMS-LV2 allows 
sample-accurate control changes.  This helps reduce the "zipper effect" 
in rapidly changing controls.

LMMS likes to expose parameters in the domain of [0,1] or [-1,1] and use 
a mapping function to convert the values to something that the 
instrument understands.  Not only does this require more computation, 
but it loses all semantic meaning to the user.  If I'm rewriting the 
thing, then I'd rather just expose values in Octaves, decibels, 
percentages, etc.  Seems minor, but this influences plugin code greatly.

If you look at much of the instrument code and GUI code, you will see 
that the instruments, although called "Plugins", are actually closely 
tied to the core of LMMS.  Also, the core LMMS functionality is not well 
aligned with a plugin interface such as LV2 or event VST.  Thus, I don't 
want a broken and confusing interface to be my target: this is in fact 
one reason why I decided to fork the project.  The LMMS code is 
unmaintainable at this point in my opinion, and I want to start 
compartmentalizing it.  What better way than to start with the least 
cohesive part first?

Despite the model-view separation in the LMMS 4 series, there is still 
tight coupling between the model data and the view.  There is some 
locking at times (which probably causes some of LMMS's xruns).  LV2 
doesn't allow (or at least strongly discourages) the GUI from accessing 
any of the plugin state but instead uses a message-passing approach, and 
for good reason.  This makes concurrency simpler, and it allows the GUI 
and plugin to live in different address spaces (say running a plugin on 
a computer and controlling it with a tablet, or even just sandboxing the 
GUI frontend from the DSP code in separate processes for reliability in 
a DAW.

Finally, regarding GUI reuse: my thought is: don't.  The little 256x256 
GUIs are getting to be rather dated; especially as screen DPIs continue 
to rise.  I couldn't imagine how cramped the GUI would look on a Retina 
display, for example.

I could probably go on, but I won't.  You will find that the LMMS-LV2 
code is in general simpler and faster than LMMS in most cases and I 
haven't even optimized it yet.  Also, the LMMS-LV2 oscillator code 
features alias-free generation of most waveforms.

Wow, sorry for the long-winded explanation, I should distill this for a 
FAQ or something.  Finally, I'd like to talk about SID and how you could 
help with this project.

If you follow the history of LMMS's SID plugin then you will find it 
uses the reSID library (or maybe a modification of it).  Thus, the SID 
plugin is not so much a priority for me since the code is already in a 
clean bundle.  I wanted to approach the difficult problems first (native 
LMMS plugins) as a proof of concept.  You'll find that the reSID library 
already performs its own voice management, waveform generation, 
envelopes, etc.  Therefore, it should be very easy to wrap this with an 
LV2-compatible interface. Something like:

process() {
   for (i=0; i<buffer_size; ++i) {
     read_next_event();
     if (i==next_event_time) {
       interpret_event_and_trigger_resid(event);
       read_next_event()
     }
     tick_resid();
   }
}

You'll see examples of this kind of code in the LMMS-LV2 
tripleoscillator source, and much of the work is planned on being broken 
out to helper functions for the other LMMS-LV2 plugins anyway.

If you would like to pull in the reSID code and write a wrapper for it, 
then I would be very much grateful; as a complete port is my ultimate 
goal.  Please let me know what you think, and thanks for your interest 
in LMMS-LV2!

Regards,
Paul

**Comment by ssj71** [comment]
Thanks for the helpful insights. I've spent probably another hour looking at the lmms code, and I did see that SId just uses reSID. It would be pretty easy to port really. I also noticed the model-view and that many of the classes are dependant on the view.
I need to look at your source more closely, because I thought lv2 ports only have 1 value per period. I've got a little experience doing lv2, but I've done each plugin as a separate project. I've got several projects on my plate right now, but I'll see if I can't get this out eventually.

**Comment by pgiblock** [comment]
You are correct, I misspoke.  The LV2 Events are sample-accurate.  This 
currently includes MIDI events.  There is a movement in LV2 to migrate 
from Controls (value-per-period) to an Event-based mechanism.  Once this 
comes into play then we will have sample-accurate controls too.

In the meantime, I'd recommend using the the existing ControlPort 
mechanism for control values.  Regarding MIDI events, it would be fairly 
easy to break the event handling code out of Triple Oscillator into some 
helper function(s).  This is responsible for reading the MIDI event 
bytes, and converting the values into notes, velocity, pitch bend 
values, etc.

Thanks

**Comment by pgiblock** [comment]
Just thought I would mention: I am refactoring the LMMS-LV2 code both for reusability (the instrument scaffolding can be reused in most instruments) and for portability (allow for Audio Units backend in addition to LV2).  To do this without macro-laden shit code, I'm moving the scaffolding code to C++.

**Comment by ssj71** [comment]
great. I'm working on some other stuff. When you feel its rebased, I'll
maybe try again. Thanks!

**Comment by ssj71** [comment]
I'll close this out. For anyone wanting a SID plugin, you can see https://github.com/ssj71/reMID.lv2 or https://www.tracktion.com/products/8bit-treats

thanks.
